FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Download and install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
	unzip awscliv2.zip && \
	sudo ./aws/install && \
	rm awscliv2.zip && \
    rm -rf aws

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]
