USE ROLE R_LYRICS_ANALYSIS;
USE WAREHOUSE WH_LYRICS_ANALYSIS;
USE DATABASE DB_LYRICS_ANALYSIS;
USE SCHEMA ANALYTICS;

CREATE TASK REFRESH_ALL_TABLES
WAREHOUSE = WH_LYRICS_ANALYSIS
AS
CALL SP_UPSERT_STG_TABLES();

CREATE TASK REFRESH_T_TABLES
WAREHOUSE = WH_LYRICS_ANALYSIS
WHEN
	(
	SYSTEM$STREAM_HAS_DATA('STR_STG_SONGS ' ) OR
	SYSTEM$STREAM_HAS_DATA('STR_STG_LYRICS' ) OR
	SYSTEM$STREAM_HAS_DATA('STR_STG_WORDS ' ) OR
	SYSTEM$STREAM_HAS_DATA('STR_STG_GENRES' )
	)
AFTER REFRESH_ALL_TABLES
AS	
CALL SP_UPSERT_T_TABLES();


CREATE TASK REFRESH_DIM_TABLES
WAREHOUSE = WH_LYRICS_ANALYSIS
WHEN
	(
	SYSTEM$STREAM_HAS_DATA('STR_T_SONGS ' ) OR
	SYSTEM$STREAM_HAS_DATA('STR_T_WORDS ' ) OR
	SYSTEM$STREAM_HAS_DATA('STR_T_ARTISTS') OR
	SYSTEM$STREAM_HAS_DATA('STR_T_GENRES' ) 
	)
AFTER REFRESH_T_TABLES
AS	
CALL SP_UPSERT_DIM_TABLES();

CREATE TASK REFRESH_FCT_TABLES
WAREHOUSE = WH_LYRICS_ANALYSIS
WHEN
	SYSTEM$STREAM_HAS_DATA('STR_T_LYRICS' )
AFTER REFRESH_DIM_TABLES
AS	
CALL SP_CALC_FCT_TABLES();
